version: "3.5"

services:
  db:
    build: .
    container_name: db
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SUCOS_VENDAS
      MYSQL_USER: adriano
      MYSQL_PASSWORD: adriano
